# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Custom configuration.

# Shell aliases.
if [ -f ~/.bash_aliases ] ; then
    source ~/.bash_aliases
fi
if [ -f ~/.zsh_aliases ] ; then
    source ~/.zsh_aliases
fi

# Host-specific configurations (these are not under version control).
if [ -f ~/.host_shrc ] ; then
    source ~/.host_shrc
fi

# Enable dircolors support.
if [ $(hash dircolors 2>/dev/null && echo 0) ] ; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
fi

if [ "x$REMOTE_SESSION_TYPE" != "x1" ] ; then
    # Only use ANSI solarized Vim theme if we're in a local session
    # (or if this environment variable has been pushed by the remote user).
    export TERMINAL_SOLARIZED=1
fi

setopt no_inc_append_history
unsetopt auto_cd
unsetopt cdable_vars
